Clarify unknown or null behavior
RadiantLabs/modeling-api-docs pull request #21
Opened 2023-09-20 18:28 UTC by kellyatradiantlabs

2023-09-20 18:39 UTC, kellyatradiantlabs commented
@joshuamzm how do I get my name file `defaulting_engine.rst` to show up in the index of pages?

2023-09-20 19:21 UTC, joshuamzm commented
> @joshuamzm how do I get my new file `defaulting_engine.rst` to show up in the index of pages?

@kellyatradiantlabs I added the Sphinx link (without the first underscore) in the `toctree` section of the index file ([fbf6302](https://github.com/RadiantLabs/modeling-api-docs/pull/21/commits/fbf63025088d23e98fa41fd9020b4c73a36e0fd1)).

Now you can see your page linked in the ToC and in the sidebar.

![image](https://github.com/RadiantLabs/modeling-api-docs/assets/10285345/ecacfbfe-7de8-4503-8dd1-1152a4d00743)

I fixed the JSON code blocks formatting and couple typos in subsequent commits.

2023-09-20 19:21 UTC, joshuamzm approved these changes

2023-09-21 15:30 UTC, jefffriesen requested changes

2023-09-21 15:30 UTC, jefffriesen commented on docs/source/defaulting_engine.rst
> +
@kellyatradiantlabs naming ResStock is slightly too much information for my comfort level. Tax assess and permits is ok. Can you describe how ResStock got the data? Such as "regional building characteristics based on historical tax codes and x, y, z".

2023-09-21 18:06 UTC, merged

2023-09-21 18:13 UTC, jefffriesen reviewed
LGTM